spring:
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create

  datasource:
    url: jdbc:h2:tcp://localhost/~/momo
    username: sa
    password:
    driver-class-name: org.h2.Driver
